# Generated by Django 4.2 on 2023-05-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentsaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsaddress',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
